In [37]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [38]:
df=pd.read_csv("./medical_insurance_cost_dataset.csv")

In [39]:
df.head(10)

,customer_id,age,gender,bmi,children,smoker,region,occupation,annual_income_usd,exercise_level,chronic_diseases,doctor_visits_per_year,hospitalizations_last_year,alcohol_consumption_per_week,insurance_plan,annual_medical_cost_usd
0,MIC100001,56,Male,25.2,2,Yes,Northeast,Driver,77885,Moderate,0,2,0,13,Basic,24353.46
1,MIC100002,29,Male,25.7,1,Yes,Northwest,Doctor,18000,High,0,2,0,3,Standard,22530.60
2,MIC100003,20,Male,30.1,1,No,Central,Teacher,85811,Low,1,5,0,1,Standard,13393.16
3,MIC100004,59,Female,18.2,1,No,Northeast,Engineer,18000,Moderate,2,10,0,8,Premium,17937.26
4,MIC100005,61,Male,31.2,5,Yes,Northwest,Nurse,42331,Moderate,0,7,0,13,Standard,22147.64
5,MIC100006,59,Male,32.1,1,No,Central,Nurse,130838,Moderate,1,8,0,11,Basic,15593.27
6,MIC100007,47,Female,26.3,0,No,Northwest,Lawyer,83769,Moderate,1,0,0,2,Basic,5170.06
7,MIC100008,54,Female,29.7,1,No,Northeast,Doctor,52921,Low,1,4,2,10,Standard,21082.43
8,MIC100009,19,Female,25.8,1,No,Southeast,Driver,62895,Moderate,1,3,1,4,Standard,15060.14
9,MIC100010,65,Male,39.0,1,No,Northwest,Office Worker,84741,Low,0,4,0,6,Gold,23103.72

In [40]:
# Separate Independent (X) and Dependent (Y) features
X = df.drop(columns=['annual_medical_cost_usd'])
Y = df['annual_medical_cost_usd']

# Print shapes
print("Shape of X (Independent Features):", X.shape)
print("Shape of Y (Dependent Feature):", Y.shape)

Shape of X (Independent Features): (7500, 15)
Shape of Y (Dependent Feature): (7500,)

In [41]:
X

,customer_id,age,gender,bmi,children,smoker,region,occupation,annual_income_usd,exercise_level,chronic_diseases,doctor_visits_per_year,hospitalizations_last_year,alcohol_consumption_per_week,insurance_plan
0,MIC100001,56,Male,25.2,2,Yes,Northeast,Driver,77885,Moderate,0,2,0,13,Basic
1,MIC100002,29,Male,25.7,1,Yes,Northwest,Doctor,18000,High,0,2,0,3,Standard
2,MIC100003,20,Male,30.1,1,No,Central,Teacher,85811,Low,1,5,0,1,Standard
3,MIC100004,59,Female,18.2,1,No,Northeast,Engineer,18000,Moderate,2,10,0,8,Premium
4,MIC100005,61,Male,31.2,5,Yes,Northwest,Nurse,42331,Moderate,0,7,0,13,Standard
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7495,MIC107496,54,Female,19.6,3,No,Northeast,Engineer,91504,Moderate,0,5,0,12,Standard
7496,MIC107497,22,Male,19.8,0,No,Central,Lawyer,66444,High,0,6,0,13,Standard
7497,MIC107498,18,Female,23.8,1,No,Northwest,Office Worker,113178,Moderate,2,7,1,12,Standard
7498,MIC107499,47,Female,33.2,0,No,Southwest,Driver,85916,Low,1,11,0,4,Basic
7499,MIC107500,23,Male,22.0,0,No,Southeast,Teacher,67477,High,0,5,0,5,Premium

In [42]:
print("\nBefore One-Hot Encoding")
print(df[['gender','smoker','region','children']])
df_encoded=pd.get_dummies(df[['gender','smoker','region','children']])
df_encoded=df_encoded.astype(int)
print("\nAfter one hot encoding")
print(df_encoded.head(5))

Before One-Hot Encoding
      gender smoker     region  children
0       Male    Yes  Northeast         2
1       Male    Yes  Northwest         1
2       Male     No    Central         1
3     Female     No  Northeast         1
4       Male    Yes  Northwest         5
...      ...    ...        ...       ...
7495  Female     No  Northeast         3
7496    Male     No    Central         0
7497  Female     No  Northwest         1
7498  Female     No  Southwest         0
7499    Male     No  Southeast         0

[7500 rows x 4 columns]

After one hot encoding
   children  gender_Female  gender_Male  smoker_No  smoker_Yes  \
0         2              0            1          0           1
1         1              0            1          0           1
2         1              0            1          1           0
3         1              1            0          1           0
4         5              0            1          0           1

   region_Central  region_Northeast  region_Northwest  region_Southeast  \
0               0                 1                 0                 0
1               0                 0                 1                 0
2               1                 0                 0                 0
3               0                 1                 0                 0
4               0                 0                 1                 0

   region_Southwest
0                 0
1                 0
2                 0
3                 0
4                 0

In [43]:
from sklearn.preprocessing import StandardScaler
numeric_feature=['age','bmi','annual_medical_cost_usd']
scaler=StandardScaler()
df[numeric_feature]=scaler.fit_transform(df[numeric_feature])
print("\nFirst 5 rows after standard scaling:")
print()
print(df[numeric_feature].head(5))

First 5 rows after standard scaling:

        age       bmi  annual_medical_cost_usd
0  1.054287 -0.578716                 0.850406
1 -0.886436 -0.477336                 0.609731
2 -1.533344  0.414815                -0.596698
3  1.269923 -1.998047                 0.003266
4  1.413681  0.637853                 0.559168

In [44]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.32, random_state=42)
print("Shape of X_train:", X_train.shape)
print("Shape of X_test:", X_test.shape)
print("Shape of Y_train:", Y_train.shape)
print("Shape of Y_test:", Y_test.shape)

Shape of X_train: (5100, 15)
Shape of X_test: (2400, 15)
Shape of Y_train: (5100,)
Shape of Y_test: (2400,)

In [45]:
X = pd.get_dummies(df.drop("annual_medical_cost_usd", axis=1), drop_first=True)
Y = df["annual_medical_cost_usd"]

In [46]:
from sklearn.linear_model import LinearRegression


model = LinearRegression()
model.fit(X_train, Y_train)

ValueError: could not convert string to float: 'MIC103476'

In [ ]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, Y_train)
y_pred=model.predict(X_test)
print("Intercept")
print(model.intercept_)
print()
print("Coefficients")
print(model.coef_)

Intercept
138.07063244036544

Coefficients
[  88.08501484  112.90106187  479.03829719 ... 6890.6198912  3532.82706248
   46.02754992]

In [ ]:
y_pred

In [ ]:
from sklearn.metrics import  r2_score

# Make predictions on the test set
print("\nPredicted Value:",y_pred[0: 11])
print("\nActual Value:",Y_test.tolist()[0: 11])

Predicted Value: [16963.76595759 13134.05723859 13342.91409253 13368.29205011
 37296.63732248 10341.26018765 10269.59502718 24852.78918979
 24115.3994868  31520.10614071 10703.85277949]

Actual Value: [15298.91, 14999.14, 11205.26, 15385.6, 41144.58, 11353.13, 10370.21, 24747.78, 21944.03, 31754.63, 14091.87]

In [ ]:
from sklearn.metrics import  r2_score
r2=r2_score(Y_test,y_pred)
print("R2 Score:",r2)

R2 Score: 0.8880629197165422

In [ ]:
# The model achieved an R² score of 0.888,
# indicating that approximately 89% of the variation in medical insurance costs is explained by the selected features.
#  This suggests the model is performing very well, though some variability remains unexplained.”

In [ ]:
import joblib
joblib.dump(model, 'insurence.pkl')
joblib.dump(scaler, 'scaler.pkl')
joblib.dump(X_train.columns.tolist(),'columns.pkl')

['columns.pkl']

In [ ]:
import os
print(os.listdir())

['.config', 'insurence.pkl', 'medical_insurance_cost_dataset (2).csv', 'insurence_model.pkl', 'medical_insurance_cost_dataset (1).csv', 'medical_insurance_cost_dataset.csv', 'scaler.pkl', 'columns.pkl', 'sample_data']

In [ ]:
from google.colab import files
files.download('insurence_model.pkl')
files.download('scaler.pkl')
files.download('columns.pkl')